Django_Project/Book_store/urls.py
from django.urls import path
from . import views

app_name = 'Book_store'

urlpatterns = [
	path('', views.showBooks, name = 'store-home'),
	path('about/', views.about, name = 'store-about'),
	path('booklist/',views.booklist, name ='store-booklist'),
	path('contact/',views.contact,name='store-contact'),
	path('booklist/<int:book_id>/',views.description,name='store-description'),
	path('results/', views.search, name='search'),
]

Django_Project/Django_Project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
import Book_store.urls
from User import views as user_views
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(Book_store.urls, namespace = 'Book_store')),
    path('register/', user_views.register, name = 'register'),
    path('login/', auth_views.LoginView.as_view(template_name = 'login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'logout.html'), name = 'logout'),
    path('profile/', user_views.profile, name = 'profile'),
    path('account/', user_views.account, name = 'account'),
    path('cart/add/<int:id>/', user_views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', user_views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/', user_views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/', user_views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', user_views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',user_views.cart_detail,name='cart_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Django_Project/Book_store/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
	name = models.CharField(max_length = 30)
	image = models.ImageField(blank = False, upload_to = 'book_cover')
	authorName = models.CharField(max_length = 30)
	price = models.IntegerField()
	description = models.TextField()
	pdfUrl = models.URLField()

Django_Project/User/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from Book_store.models import Book
from cart.cart import Cart
# Create your models here.

class Profile(models.Model):
	user = models.OneToOneField(User, null=True, on_delete = models.CASCADE,unique=True)
	name = models.CharField(max_length=64, default=" ")
	image = models.ImageField(default="profile_pic/default.jpg", upload_to = 'profile_pic',null=True)
	def __str__(self):
		return f'{self.user.username} Profile'

class Account(models.Model):
	user = models.OneToOneField(User,related_name="user", null=True, on_delete = models.CASCADE,unique=True)
	def __str__(self):
		return f'{self.user.username} Account'

Django_Project/cart/models.py
from django.db import models

# Create your models here.

Django_Project/User/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):
	email = forms.EmailField()
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['name','image']

Django_Project/Book_store/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from Django_Project import settings
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from Book_store.models import Book



def search(request):
	search_term = ''
	search_results = ''
	books=''
	if 'search' in request.GET:
		search_term = request.GET['search']
		search_results = Book.objects.all().filter(id=search_term) 
	books = Book.objects.all()
	return render(request, 'search_result.html', {'books' : books, 'search_results': search_results })    
# Create your views here.
def description(request,book_id):
	book=get_object_or_404(Book, id=book_id)
	return render(request,"description.html", dict(book=book))
def about(request):
	return render(request, "about.html")

def booklist(request):
	books = Book.objects.all()
	return render(request,"booklist.html", {'books' : books})

# def sendmail(request):
# 	subject = "Order successfully palced"
# 	msg = "Your order from SOFTCOVER is on the way"
# 	to = "User."
# 	res = send_mail(subject, msg, settings.EMAIL_HOST_USER, [to])
# 	return render(request, "confirm.html")

def showBooks(request):
	return render(request, "home.html")
def contact(request):
	return render(request,"contact.html")

Django_Project/User/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required
from .models import Profile
from Book_store.models import Book
from cart.cart import Cart
# Create your views here.

def account(request):
    return render(request, 'account.html')



def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Your account has been crteated. Now you can login!')
            return redirect('login')
    else:	
        form = UserRegisterForm()
    return render(request, 'register.html', {'form' : form})


@login_required
def profile(request):
    Profile.objects.get_or_create(user=request.user)
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,request.FILES,instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'profile.html', context)

@login_required
def cart_add(request, id):
    cart = Cart(request)
    product = Book.objects.get(id=id)
    cart.add(product=product)
    return redirect("cart_detail")


@login_required
def item_clear(request, id):
    cart = Cart(request)
    product = Book.objects.get(id=id)
    cart.remove(product)
    return redirect("cart_detail")


@login_required
def item_increment(request, id):
    cart = Cart(request)
    product = Book.objects.get(id=id)
    cart.add(product=product)
    return redirect("cart_detail")


@login_required
def item_decrement(request, id):
    cart = Cart(request)
    product = Book.objects.get(id=id)
    cart.decrement(product=product)
    return redirect("cart_detail")


@login_required
def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect("cart_detail")


@login_required
def cart_detail(request):
    return render(request, 'cart_detail.html')

Django_Project/cart/views.py
from django.shortcuts import render

# Create your views here.

Django_Project/Book_store/templates/about.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    About Us
{% endblock title %}

<!--link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"-->

{% block content %}
    <div>
        <img src="{% static '/images/unnamed.png' %}" align='left' alt="Simply Easy Learning" width="140" height="140"><br>
    	<br><br><h1 align='center'><font >ABOUT US</font></h1><br><br>
           <h5>Our company is a comprehensive online bookstore for both
                books and other products of every point of knowledge.
                Our philosophy is based on information, communication and
                 education, which we feel should be balanced
                 out with a daily dose of knowledge, wisdom,
                  understanding (overstanding, and innerstanding).
            <br><br> <P>Our website features books from every literary genre,
                 allowing us to appeal to any particular
                 taste a customer may have. Can't find what you're looking for?
                  We can order the book for you.
    In just a few business days, we'll get that book to you so that you can enjoy
     a quiet evening at home, prepare a nice
     gift for someone or simply use it to expand your horizons.
    Our experienced staff can assist you in selecting the right literature
     and will be glad to go that extra mile for you!</P></h5> 
    <br><br>
    <style>
            a.button{
                font: bold 11px;
                text-decoration:white;
                background-color: rgb(55, 57, 70);
                color: #f7f7f7;
                padding: 4px 8px 4px 8px;
                border-top: 1px solid rgb(39, 39, 39);
                border-right: 1px solid #333333;
                border-bottom: 1px solid #333333;
                border-left: 1px solid rgb(37, 37, 37);
              }
        </style>
    <a  href="{% url 'Book_store:store-contact' %}" class="button">CONTACT US</a>
        </div>
{% endblock %}

Django_Project/Book_store/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    {% load static %}
	<title>
		{% load static %}
		{% block title %}
		    VEDANAM
		{% endblock title %}
	</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<style>
			body{
				background-image: url("{% static 'images/hhhh.jpg' %}");
				background-color: white;
				background-repeat: no-repeat;
				background-size:cover;
				background-attachment: fixed;
			}
	</style>
	
  <body>
	<header class="site-header">
  		<nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
    		<div class="container">
      			<a class="navbar-brand mr-4" href="{% url 'Book_store:store-home' %}">VEDANAM</a>
  				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
  				<span class="navbar-toggler-icon"></span>
  				</button>
      			<div class="collapse navbar-collapse" id="navbarToggle">
        			<div class="navbar-nav mr-auto">
	          			<!--a class="nav-item nav-link" href="{% url 'Book_store:store-home' %}">Home</a-->
						  <a class="nav-item nav-link" href="{% url 'Book_store:store-about' %}">About</a>&emsp;&emsp;&emsp;
						  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
						  {% if user.is_authenticated %}
						  <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'Book_store:search' %}">
							  <input class="form-control mr-sm-2" type="search" placeholder="Search for books" aria-label="Search" name="Search">
							  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">-></button>
						  </form>
						  {% endif %}
        			</div>
       			 	<!-- Navbar Right Side -->
        			<div class="navbar-nav">
                {% if user.is_authenticated %}
								<a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
								<a class="nav-item nav-link" href="{% url 'Book_store:store-booklist' %}">Booklist</a>
								<a class="nav-item nav-link" href="{% url 'cart_detail' %}">Cart</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                {% else %}
          			<a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
          			<a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
        			</div>
              {% endif %}
      			</div>
    		</div>
  		</nav>
	</header>
	<main role="main" class="container">
  		<div class="row">
    		<div class="col-md-8" >
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
		  {% endif %}
		{% block content %}
          {% endblock %}
			</div>
			<img src="{% static '/images/image.jpg' %}" align="right" alt="Simply Easy Learning" width="370" height="580" >
    		<!-- <div class="col-md-4">
      			<div class="content-section">
        			<h3>Our Sidebar</h3>
       				 <p class='text-muted'>You can put any information here you'd like.
			         <ul class="list-group">
			            <li class="list-group-item list-group-item-light">Latest Posts</li>
			            <li class="list-group-item list-group-item-light">Announcements</li>
			            <li class="list-group-item list-group-item-light">Calendars</li>
			            <li class="list-group-item list-group-item-light">etc</li>
			         </ul>
        			</p>
      			</div>
    		</div> -->
  		</div>
	</main>    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	</body>
	</head>
</html>

Django_Project/Book_store/templates/booklist.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Home
{% endblock title %}

{% block content %}
{% if user.is_authenticated %}
<br><h1 align="center"><font>  OUR BOOKS</font></h1><br>
<table border="1px" align="center" cellpadding="10px" cellspacing="0px">
        <tr>
                <td><h6>COVER</h6></td>
                <td><h6>BOOKNAME</h6></td>
                <td><h6>AUTHOR</h6></td>
                <td><h6>PRICE</h6></td>
                <td><h6>ADD TO CART</h6></td>
        </tr>
        {% for book in books %}
        <tr>
            <td><img src="{{ book.image.url }}" alt="Simply Easy Learning" width="80" height="110"></td>
            <td><a  href="{% url 'Book_store:store-description' book.id %}"><font color="black" style="font-weight: bold;">{{book.name}}</font></a></td>
            <td>{{book.authorName}}</td>
            <td align="center">${{book.price}}</td>
            <td align="center"><a  href="{% url 'cart_add' book.id %}">
                <font size="3" color="green" style="font-weight: bold;">ADD</font></a></td>
            <!--td><a href="/edit/{{student.id}}">Edit</a></td>
            <td><a href="/delete/{{student.id}}" onclick="return check()">Delete</a></td-->
        </tr>
        {% endfor %}
    </table>
    {% endif %}
    <!-- {% if user.is_authenticated %}
		{% for book in books %}
    		<h1>hi</h1>
    		{{ book.bookName }}
    		{{ book.bookImage }}
    		{{ book.authorName }}
    		{{ book.price }}
    		{{ book.description }}
    	{% endfor %}
    {% endif%} -->
{% endblock %}


Django_Project/Book_store/templates/confirm.html
{% extends "base.html" %}

{% block title %}
    Confirm
{% endblock title %}

{% block content %}
    
{% endblock content %}

Django_Project/Book_store/templates/contact.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    About Us
{% endblock title %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

{% block content %}
    <div>
        <img src="{% static '/images/unnamed.png' %}" align='left' alt="Simply Easy Learning" width="140" height="140">
    	<br><br><h5 style=font-size:55px><font color="black"> &emsp; V E D </font>A N A M</h5><br><br>
           <h5 align='center' style = "font-family:georgia,garamond,serif;font-style:italic;margin-left: 7.5em;"><br><br>
           <img src="{% static '/images/saksham.jpg' %}" alt="saksham" width="65" height="65" style="border-radius:10px;border:2px solid #2a2a2a" >
           <a  href="http://www.linkedin.com/in/sakshambaranwal"><font color= #2a2a2a style="font-weight: bold;">SAKSHAM KUMAR</font></a>&emsp;&emsp;
           </h5> 
    <br><br>
    </div>
{% endblock %}

Django_Project/Book_store/templates/description.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    About Us
{% endblock title %}

<!--link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"-->

{% block content %}
{% if user.is_authenticated %}
    <div>
        <img src="{{ book.image.url }}" align='left' alt="Simply Easy Learning" width="180" height="240"><br>
        <br><br><br><h1 align='center'><font >{{book.name}}</font></h1>
        <h5 align='right'><font >-{{book.authorName}}</font></h5><br><br><br><br>
           <h5>{{book.description}}</h5> 
    <br><br>
    <h2 align='left'>Price: ${{book.price}}</h2><br>
    <style>
            a.button{
                font: bold 11px;
                text-decoration:white;
                background-color: rgb(55, 57, 70);
                color: #f7f7f7;
                padding: 4px 8px 4px 8px;
                border-top: 1px solid rgb(39, 39, 39);
                border-right: 1px solid #333333;
                border-bottom: 1px solid #333333;
                border-left: 1px solid rgb(37, 37, 37);
              }
        </style>
    <a  href="{{book.pdfUrl}}" class="button">READ ONLINE FOR FREE</a>&emsp;&emsp;&emsp;&emsp;
    <a href="{% url 'cart_add' book.id %}" class="button">ADD TO CART</a>
        </div>
{% else %}
<div class="border-top pt-3">
    <a href="{% url 'login' %}" class="ml-2" title="">Sign In to continue</a>
</div>
{% endif %}
{% endblock %}

Django_Project/Book_store/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Home
{% endblock title %}

{% block content %}
<div>
        <img src="{% static '/images/unnamed.png' %}" align='left' alt="Simply Easy Learning" width="140" height="140">
    	<br><br><h5 style=font-size:55px><font color="black"> &emsp; V E D </font>A N A M</h5><br><br>
           <h2>WELCOME TO OUR BOOKSTORE!</h2><br><h5>
            Nowadays, the network plays an import role in people’s life. 
            In the process of the improvement of the people’s living 
            standard,people’s demands of the life’s quality and efficiency 
            is more higher,the traditional bookstore’s inconvenience gradually
            emerge, and the online bookstore has to be gradually used in public. <br><br> <P>  
            The online bookstore is a revolution of book industry. The traditional 
            bookstores’ operation time,address and space is limited, so the types 
            of books to find receives a degree of restriction. But the 
            online bookstore breaks the management mode of traditional bookstore.
            As long as you have a computer, you can read the book anywhere,saving 
            time and effort, shortening the time of book selection link effectively. 
            The online bookstore system based on this principle provides convenience
            and service to people.<br><br></h5> <h4>Enjoy reading online books with us.<br>
                {% if not user.is_authenticated %}
            To check the books available here, Please Login
        {% endif %}</h4>





            </P>
            </div>
            

    <!-- {% if user.is_authenticated %}
		{% for book in books %}
    		<h1>hi</h1>
    		{{ book.bookName }}
    		{{ book.bookImage }}
    		{{ book.authorName }}
    		{{ book.price }}
    		{{ book.description }}
    	{% endfor %}
    {% endif%} -->
{% endblock %}

Django_Project/Book_store/templates/search_result.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Search Results
{% endblock title %}

{% block content %}
{% if user.is_authenticated %}
<br><h1 align="center"><font>  SEARCH RESULT</font></h1><br>
<table border="1px" align="center" cellpadding="10px" cellspacing="0px">
        <tr>
                <td><h6>COVER</h6></td>
                <td><h6>BOOKNAME</h6></td>
                <td><h6>AUTHOR</h6></td>
                <td><h6>PRICE</h6></td>
                <td><h6>ADD TO CART</h6></td>
        </tr>
        {% for book in search_results %}
        <tr>
            <td><img src="{{ book.image.url }}" alt="Simply Easy Learning" width="80" height="110"></td>
            <td><a  href="{% url 'Book_store:store-description' book.id %}"><font color="black" style="font-weight: bold;">{{book.name}}</font></a></td>
            <td>{{book.authorName}}</td>
            <td align="center">${{book.price}}</td>
            <td align="center"><a  href="{% url 'cart_add' book.id %}">
                <font size="3" color="green" style="font-weight: bold;">ADD</font></a></td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
{% endblock %}


Django_Project/User/templates/cart_detail.html
{% extends "base.html" %}
{% load static %}
{% load cart_tag %}

{% block title %}
    Home
{% endblock title %}

{% block content %}
{% if user.is_authenticated %}
<h1 align="center"><font> CART</font></h1>
<!--table border="1px" align="center" cellpadding="10px" cellspacing="0px">
        <tr>
                <td><h6>COVER</h6></td>
                <td><h6>BOOKNAME</h6></td>
                <td><h6>QUANTITY</h6></td>
                <td><h6>PRICE</h6></td>
        </tr-->

        {% for key,value in request.session.cart.items %}
        <div  style='box-shadow: 0 2px 5px 0 rgba(0,0,0,0.16),0 2px 10px 0 rgba(0,0,0,0.12);'>
              <img src="{{ value.image}}" width="120" height="166" align='left'>
              <a  href="{% url 'item_clear' value.product_id %}" >
                <h6 style="font-weight: bold;  color:red;" align='right'>Delete&emsp;&emsp;</h6></a>
              <h4 align="left">  {{ value.name }}</h4>
              <h5>{{value.authorName}}</h5><br>
              <h5 align="left">  ${{ value.price|multiply:value.quantity}} </h5><br>
              <h5 style="font-weight: bold;  color:green;" align='left'>
              <a  href="{% url 'item_decrement' value.product_id %}">
                -</a>
               {{value.quantity}} 
            <a  href="{% url 'item_increment' value.product_id %}">
                +&emsp;</a> </h5>
              <!--button>Wishlist</button-->
          </div><br>
        <!--tr>
            <td><img src="{{ value.image}}" alt="Simply Easy Learning" width="80" height="110"></td>
            <td><a  href="{% url 'Book_store:store-description' value.product_id %}"><font color="black" style="font-weight: bold;">{{value.name}}</font></a></td>
            <td align="center">
                <a  href="{% url 'item_decrement' value.product_id %}">
                    <font size="3" color="green" style="font-weight: bold;">-</font></a>
                <font size="3" color="green" style="font-weight: bold;">{{value.quantity}}</font>
                <a  href="{% url 'item_increment' value.product_id %}">
                    <font size="3" color="green" style="font-weight: bold;">+</font></a>
                            
            </td>
            <td align="center">${{ value.price|multiply:value.quantity}}</td-->
            <!--td><a href="/edit/{{student.id}}">Edit</a></td>
            <td><a href="/delete/{{student.id}}" onclick="return check()">Delete</a></td-->
        <!--/tr-->
        {% endfor %}<br>
    <h3 align='right'>Total: $ {{cart_total_amount}}&emsp;&emsp;&emsp;&emsp;&emsp; </h3><br>
    {% endif %}
    <!-- {% if user.is_authenticated %}
		{% for book in books %}
    		<h1>hi</h1>
    		{{ book.bookName }}
    		{{ book.bookImage }}
    		{{ book.authorName }}
    		{{ book.price }}
            {{ book.description }}
    	{% endfor %}
    {% endif%} -->
{% endblock %}


Django_Project/User/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Register
{% endblock title %}

{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Login</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button type="submit" class="btn btn-outline-info">Login</button>
			</div>
		</form>
		<div class="border-top pt-3">
			<small class="text-muted">Need An Account? <a href="{% url 'register' %}" class="ml-2" title="">Sign Up</a></small>
		</div>
	</div>
{% endblock %}

Django_Project/User/templates/logout.html
{% extends "base.html" %}
{% block title %}
    Logout
{% endblock title %}

{% block content %}
	<h2>You have been logged out successfully!</h2>
		
	<div class="border-top pt-3">
		<a href="{% url 'login' %}" class="ml-2" title="">Sign In again</a>
	</div>
{% endblock %}

Django_Project/User/templates/profile.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.profile.name }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Profile Info</legend>
              {{ u_form|crispy }}
              {{ p_form|crispy }}
          </fieldset>
          <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Update</button>
          </div>
      </form>
    </div>
{% endblock content %}

Django_Project/User/templates/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Register
{% endblock title %}

{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Join Today</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button type="submit" class="btn btn-outline-info">Sign Up</button>
			</div>
		</form>
		<div class="border-top pt-3">
			<small class="text-muted">Already Have An Account? <a href="{% url 'login' %}" class="ml-2" title="">Sign In</a></small>
		</div>
	</div>
{% endblock %}